### ISSUE TITLE
Support for vManage 20.6.5.5?

### ISSUE THREAD

**Issue by lgbrownjr** [weiborao/vmanage-dailybackup#3]
I know this has been awhile, but is this script working on vManage 20.6.5.5?  The error i am getting is:
`Start to backup database.
Traceback (most recent call last):
  File "/home/cis_network/vmanage/dailybackup.py", line 162, in <module>
    main()
  File "/home/cis_network/vmanage/dailybackup.py", line 135, in main
    backup_job.run_backup()
  File "/home/cis_network/vmanage/dailybackup.py", line 73, in run_backup
    self.backup_ret = self.net_connect.send_command(backup_cmd)
  File "/home/cis_network/vmanage/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 110, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
  File "/home/cis_network/vmanage/venv/lib/python3.10/site-packages/netmiko/utilities.py", line 595, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/cis_network/vmanage/venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 1824, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: '507Lab\\-vManage\\#' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.`

End of the job.

**Comment by weiborao** [comment]
I don't have a test environment now. But I think that maybe after the request nms configuration-db backup command was run, the netmiko expected the pattern of '507Lab\-vManage\#' but not find it.
